### PR TITLE
Update snekset aa1 to implement 2 (Migrate: Newest Engine Release 06.08.2020)

### PR DESCRIPTION
**Pull request by schettn**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Documentation (non-breaking change which adds documentation)
 - [x] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently the templates and urls does not apply with the newest engine release.
- Currently there is no template for getting user pages

**What is the new behavior (if this is a feature change)?**
- Now the templates and urls are adjusted for the newest engine release.
- Now there is a query and task for getting user pages.

**Other information**:
- 🐍

### CODE REVIEW

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Review by pinterid — APPROVED** [review]
Looks good

**Review by Aichnerc — APPROVED** [review]
LGTM

**Review by kleberbaum — APPROVED** [review]
Should be ok to merge.

**Pull request merged**
